### PR TITLE
Start project

### PR DESCRIPTION
**Pull request by iordic**

### CODE REVIEW

**Comment by tanayag** [comment]
make it class int
and use method `__add__`
and concatenate it

**Comment by iordic** [comment]
Done.

**Comment by tanayag** [comment]
it should be
`b = str(n.number)`
I will edit :) 
and lets not use arguments like end=" "
its not supported by python 2

**Comment by tanayag** [comment]
@iordic lol
I did some edits!
We need to make module shitty :p lol

**Comment by iordic** [comment]
I was thinking in Python3, it's the future! 😆

**Pull request merged**
